### ISSUE TITLE
`NXdata` group `@axes` attribute

### ISSUE THREAD

**Issue by g5t** [scipp/scippnexus#196]
How `@axes` should be encoded/interpreted has been discussed previously in #145 
   - there, I believe the discussion was about `@axes` applied to the `dataset` named 'DATA'

Comparing what the NeXus standard says regarding how the `@axes` attribute should be encoded when applied to the 'DATA' `dataset` and its containing `NXdata` group, there is some ambiguity.

Namely, notice that both use the term 'array'
> Defines the names of the coordinates (independent axes) for this data set as a colon-delimited array.
>
> &mdash; [`NXdata/data @axes`](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata-data-axes-attribute)

> When axes contains multiple strings, it must be saved as an actual array of strings and not a single comma separated string.
>
>  &mdash; [`NXdata @axes`](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata-axes-attribute) 

Where this becomes ambiguous, is in that HDF5 allows for array-valued attributes (which [h5py reads as numpy arrays](https://docs.h5py.org/en/stable/high/attr.html)), and `scippnexus` has interpreted both 'colon-delimited array' and 'actual array of strings' to specify a single string with axes names separated by literal ':' characters.

## Issue
If someone interprets 'actual array of strings' to mean 'array-valued attribute with string elements', then creates a NeXus HDF5 file, like the one attached; that file can not be opened by `scippnexus` due to the use of the `split` method here:
https://github.com/scipp/scippnexus/blob/58ffbbe67e90bf3341a7589e89e00e36859ba712/src/scippnexus/nxdata.py#L160

## Possible solution
Add a check that `self._signal_axes` is a `str` before attempting to use `.split`, or alternately a check if it is a numpy array, e.g., replacing the quoted line 160 by
```python
            self._signal_axes = tuple(self._signal_axes if isinstance(self._signal_axes, np.ndarray) else self._signal_axes.split(':'))
```

## Alternate solution
If the interpretation of 'actual array of strings' should be limited to 'colon-delimited array' like the 'DATA' dataset attribute, 
petition the NeXus committee to clarify their boxed-note for the group attribute.

**Comment by g5t** [comment]
I failed to attach this file previously: [monitor.h5.zip](https://github.com/scipp/scippnexus/files/14281853/monitor.h5.zip)

> :warning: Other unresolved issues prevent `scippnexus` from loading the group at `/entry/instrument/007_frame_0`

**Comment by SimonHeybrock** [comment]
> Where this becomes ambiguous, is in that HDF5 allows for array-valued attributes (which [h5py reads as numpy arrays](https://docs.h5py.org/en/stable/high/attr.html)), and `scippnexus` has interpreted both 'colon-delimited array' and 'actual array of strings' to specify a single string with axes names separated by literal ':' characters.

That is not correct. Scipp implements both, see the comments in the relevant code: https://github.com/scipp/scippnexus/blob/58ffbbe67e90bf3341a7589e89e00e36859ba712/src/scippnexus/nxdata.py#L153-L164

`NXdata@axes` is an "actual array of strings" (as the standard says), and the older NXdata/DATA@axes is a "colon-delimited array".


> ## Issue
> 
> If someone interprets 'actual array of strings' to mean 'array-valued attribute with string elements', then creates a NeXus HDF5 file, like the one attached; that file can not be opened by `scippnexus` due to the use of the `split` method here:

The `self._signal_name` corresponds to the `NXdata/DATA@axes` attr, *not* the `NXdata@axes` attr. The former is a legacy way of defining axes, and I am not sure it is worth adding workarounds for broken legacy files?

 
> Add a check that `self._signal_axes` is a `str` before attempting to use `.split`, or alternately a check if it is a numpy array, e.g., replacing the quoted line 160 by
> 
> ```python
>             self._signal_axes = tuple(self._signal_axes if isinstance(self._signal_axes, np.ndarray) else self._signal_axes.split(':'))
> ```

If we fail to load (instead of using a fallback) then I agree we should improve that. However I am hesitant to *interpret* such a non-standard attribute. If we do that, then tomorrow someone will come and say "I thought it was comma-delimited, not colon, can we also support that?", i.e., where do we draw the line? Given that I have not seen an offending `NXdata/DATA@axes` in the files from various facilities that I have tried, I am not sure it is worth it.

As a workaround for loading such files, note that it is possible to pass customized application definitions to `snx.File`. One could, e.g., remove the `NXdata` from the defs, so it will be loaded as a plain group:

```python
import scippnexus as snx

my_definitions = snx.base_definitions()
del my_definitions['NXdata']
with snx.File(filename, definitions=my_definitions) as f:
    dg = f[()]
```

**Comment by g5t** [comment]
I see now that [only `NXdata@axes`](https://manual.nexusformat.org/datarules.html#associating-multi-dimensional-data-with-axis-data) is recommended -- but why this information is not _also_ listed on the `NXdata` page is a mystery.

My issue seems to stem from having a `NXdata` group nested inside of a `NXmonitor`, and the internal group getting picked-up as the _monitor_'s `self._signal_axes`.
Is it not valid to replace `NXmonitor/data` (an [optional `NX_NUMBER`](https://manual.nexusformat.org/classes/base_classes/NXmonitor.html#nxmonitor)` by a more-complete `NXdata` group?
